"""create stop_budget_overrides table

Revision ID: 5680fbda6800
Revises: bc97b2f70fec
Create Date: 2026-08-22 11:13:31.032893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5680fbda6800"
down_revision: str | Sequence[str] | None = "bc97b2f70fec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stop_budget_overrides",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stop_id", sa.UUID(), nullable=False),
        sa.Column(
            "transport_cost_override", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "stay_cost_override", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["stop_id"], ["stops.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stop_budget_overrides_stop_id"),
        "stop_budget_overrides",
        ["stop_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stop_budget_overrides_stop_id"), table_name="stop_budget_overrides"
    )
    op.drop_table("stop_budget_overrides")
    # ### end Alembic commands ###
