"""create trip_shares table

Revision ID: 6b10fd101173
Revises: 5680fbda6800
Create Date: 2026-08-22 11:30:34.874040

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b10fd101173"
down_revision: str | Sequence[str] | None = "5680fbda6800"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_shares",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trip_shares_slug"), "trip_shares", ["slug"], unique=True)
    op.create_index(
        op.f("ix_trip_shares_trip_id"), "trip_shares", ["trip_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_shares_trip_id"), table_name="trip_shares")
    op.drop_index(op.f("ix_trip_shares_slug"), table_name="trip_shares")
    op.drop_table("trip_shares")
    # ### end Alembic commands ###
