"""create cities and activities tables

Revision ID: a65292532b25
Revises: de3d0b9f4691
Create Date: 2026-08-22 09:43:04.210851

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a65292532b25"
down_revision: str | Sequence[str] | None = "de3d0b9f4691"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("cost_index", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("popularity_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country", name="uq_cities_name_country"),
    )
    op.create_index(op.f("ix_cities_country"), "cities", ["country"], unique=False)
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_table(
        "activities",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("city_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "sightseeing",
                "food",
                "adventure",
                "culture",
                "nightlife",
                "other",
                name="activity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "cost",
            sa.Numeric(precision=8, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("duration_mins", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activities_city_id"), "activities", ["city_id"], unique=False
    )
    op.create_index(op.f("ix_activities_type"), "activities", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_type"), table_name="activities")
    op.drop_index(op.f("ix_activities_city_id"), table_name="activities")
    op.drop_table("activities")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_country"), table_name="cities")
    op.drop_table("cities")
    # ### end Alembic commands ###
