"""create trip_activities table

Revision ID: bc97b2f70fec
Revises: ec8af32aea08
Create Date: 2026-08-22 10:25:13.781183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc97b2f70fec"
down_revision: str | Sequence[str] | None = "ec8af32aea08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trip_activities",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("stop_id", sa.UUID(), nullable=False),
        sa.Column("activity_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=True),
        sa.Column("cost_override", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["stop_id"], ["stops.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "stop_id",
            "scheduled_date",
            "order_index",
            name="uq_trip_activities_stop_date_order",
        ),
    )
    op.create_index(
        op.f("ix_trip_activities_activity_id"),
        "trip_activities",
        ["activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trip_activities_stop_id"), "trip_activities", ["stop_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_activities_stop_id"), table_name="trip_activities")
    op.drop_index(op.f("ix_trip_activities_activity_id"), table_name="trip_activities")
    op.drop_table("trip_activities")
    # ### end Alembic commands ###
